# Generated by Django 5.1.1 on 2024-09-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
