# Generated by Django 5.1.1 on 2024-09-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_image_data_image_is_validated_image_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at',
        ),
    ]
